;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname ex80) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp")) #f)))
(define (buy-ticket m)
  ...
  (movie-title m)
  ...
  (movie-director m)
  ...
  (movie-year m)...)

(define (feed pet)
  ...
  (pet-name pet)
  ...
  (pet-number pet))

(define (listen cd)
  ....
  (CD-artist)
  ...
  (CD-title)
  ...
  (CD-price)
  ...)

(define (wear s)
  ...
  (sweater-material s)
  ...
  (sweater-size s)
  ...
  (sweater-color)
  ...)